function [log, accumWinnings] = facesDiscriminationTest3 (MWfaces,Originals, nMorphs, N,morphs_division, Repetitions,Instructions,RewardMagnitude, accumWinnings, flipText,training)

% This function execute Discrimination Test.
% In each trial one morph from the axis between the original faces is presented
% followed by 2afc between the original faces and the participant sked to
% choose the most similar to the face he saw.

% Inputs:
%       * Origonals - the original faces the comprise the morphs
%       * nMorphs number of morphs on the axis
%       * N -number of original stimuli (faces) 
%       * morphs_division - division of the morphs to which original morphs
%       each morph is closer. to calculate the correct response
%       * Repetititions - number of repetitions of each trial
%       * Instructions- the specific JPG file of the insstructions to use
%       * RewardMagnitude - points gain or lose in each trial
%       * accumWinnings - accumulated reward so far
%       * flipText = for some computers the hebrew text is fliped to flip it back set this value to 1



% Outputs:
%     log- struct holding the following fields:
%       * RT - a vector size NumOfTrials*1 holds the response time for each trial
%       * correct -  a vector size numOfTtials*1, that holds for each trial if the response was correct(1) or incorrect choice (-1),  for the middle morphs there is no correct answer (0)
%       * shuffledTrialsOrder - The specific order of trials for this participant
%       * originalOrder - The indices to put in the prameters to organize back in the original order ( [~, originalOrder] = sort(shuffledTrialsOrder) )
%       * Response - a vector size numOfTtials*1, that holds the actual key press by the participant - left(1) or down (2) right (3)
%       * subjectChoice - a vector size numOfTtials*1, that holds the subjects choice of face (1, 2 or 3) with respect to the original stimuli order (face 1 face 2 of face 3), and not the choice according to location on the screen!
%       * ExpTime - the time of this session in secs
%       * faces - the source faces that were use
%       * WrongKeyTrial - vectors that holds all the number of trails   that the subject press wrong key
%       * WrongKeyMorph - holds the specific morph that was presented when the subject pressed the wrong key
%       * TooSlowTrial - vectors that holds all the number of trails that the response were too slow
%       * TooslowMorph - holds the specific morph that was presented when the subject responded too slow
%       * accumWinnings - holds the accumulated reward including this session
%       * log.RT_training - a vector size NumOfTrialsTraining*1 holds the response time for each trial in the training
%       * log.Response_training - a vector size numOfTtials*1, that holds the actual key press by the participant - left(1) or right(2)
%       * log.wrongKeyTrial_training - vectors that holds all the number of trails that the subject press wrong key during the training
%       * log.wrongKeyMorph_training - holds the specific morph that was presented when the subject pressed the wrong key during the training
%       * log.tooSlowTrial_training - vectors that holds all the number of trails that the response were too slow during the training
%       * log.tooSlowMorph_training - holds the specific morph that was  presented when the subject responded too slow during the training





HideCursor(),

% check input
if nargin < 3
    error('not enough input arguments')
end

global facesPathMen facesPathWomen textPath trainingPath

% men or woman stimuli
if MWfaces=='m'
    facesPath=facesPathMen
elseif MWfaces=='w'
    facesPath=facesPathWomen
else
    error ('Choose men or woman faces stimuli (m/w)')
end



%% Initial screen settings:

% Get the screen numbers
screens = Screen('Screens');

% Draw to the external screen if avaliable
screenNumber = max(screens);

% open a black screen
black = BlackIndex(screenNumber);

[windowPtr, windowRect] = Screen('OpenWindow', screenNumber, black);% windowPtr - open display, window windowRect - size of display window
[~, screenYpixels] = Screen('WindowSize', windowPtr);

KbName('UnifyKeyNames'); %to be able to use the name rather then keykode of keys.

% faceDim - size (rectangle) of stimulus
tmp_image=imread([facesPath,'originals\1.jpg']);
faceDim = size(tmp_image,1); %only square stimuli

% compute spatial locations for stimuli
locationN = locN(N,windowRect,faceDim);

% Initialize the keyboard queue to collect resopnse
PsychHID('KbQueueCreate') %Creates a queue for events generated by an input device (keyboard, keypad, mouse, ...).
PsychHID('KbQueueStart') %Starts the queue for input events generated by a device.
PsychHID('KbQueueFlush',[], 3); %Flushes all scored and unscored keyboard events from a queue.

numOfTrials = nMorphs*Repetitions;
trials=repmat((1:nMorphs)',Repetitions,1);

% Shuffle the trials for each participant
index=randperm(length(trials));
[shuffledTrialsOrder] = trials(index);
[~, originalOrder] = sort(index); % originalOrder are the indices to go back to the original order before shuffeling the trials

IM = cell(N);

% num of trials in the
numOfTrialsTraining=6;

% set keys
rightKey = KbName('RightArrow'); % this should be the code of the right arrow
leftKey = KbName('LeftArrow'); % this should be the code of the left arrow
downKey = KbName('DownArrow');%down arrow
escapeKey = KbName('Escape'); % KbName('ESCAPE'); 

% alocate space for  variables
Response = nan(numOfTrials,1);
Response_training = nan(numOfTrialsTraining,1);
RT = nan(numOfTrials,1);
correct = zeros(numOfTrials,1);
RT_training = nan(numOfTrialsTraining,1);
WrongKeyTrial = nan(numOfTrials,1);
WrongKeyMorph = nan(numOfTrials,1);
TooSlowTrial = nan(numOfTrials,1);
TooSlowMorph = nan(numOfTrials,1);
WrongKeyTrial_training = nan(numOfTrialsTraining,1);
WrongKeyMorph_training = nan(numOfTrialsTraining,1);
TooSlowTrial_training = nan(numOfTrialsTraining,1);
TooSlowMorph_training = nan(numOfTrialsTraining,1);
subjectChoice = zeros(numOfTrials,1); % with respect to original face order;


startTime = GetSecs;
%% Show instructions
i=1;
while i<5
    inst = imread([textPath,Instructions{i},'.jpg']);
    Screen('PutImage', windowPtr, inst);
    Screen('Flip',windowPtr);
    keyIsDown = 0;
    WaitSecs(0.2)
    
    while ~keyIsDown
        [keyIsDown,secs,KeyCode] = PsychHID('KbCheck',0);
        if keyIsDown==1
            keyPressed = find(KeyCode);
            switch keyPressed
                case leftKey
                    i=i+1;
                case rightKey
                    if i>1
                       i=i-1;
                    else 
                       i=i+1;  
                    end     
                case escapeKey
                    sca
            end
            WaitSecs(0.1)
        end
    end
end
WaitSecs(0.5)

inst_break = imread([textPath, 'instructions_break.jpg']);
Screen('PutImage', windowPtr, inst_break);
Screen('Flip',windowPtr);

%% Training
done_training=0;
if training=='y'
   while done_training == 0
         TrainingDiscriminationTest3
    end
end

%%
WK = 1; %index for wrong key trials
TS = 1; %index for too slow trials
trial = 1;

%% Trial loop

while trial<=numOfTrials
    %break in the middle of the experiment
    if trial == numOfTrials/2+1
        break_txt = imread([textPath,'break.jpg']);
        textureIndex1 = Screen('MakeTexture', windowPtr, break_txt);
        Screen('DrawTexture', windowPtr, textureIndex1, [] ,[]);
        Screen('Flip', windowPtr);
        KbWait([],2); %waits for a new key press
    end
    
    % first screen show one morph
    morphNum = shuffledTrialsOrder(trial);
    morph = imread([facesPath,num2str(morphNum),'.jpg']);
    textureIndex1 = Screen('MakeTexture', windowPtr, morph);
    Screen('DrawTexture', windowPtr, textureIndex1);%, [] ,[638.5 119 1281.5 762]);
    Screen('Flip', windowPtr);
    WaitSecs(1.5)
    
    % second screen - all the original and the participant need to choose
    % which one is the most similar to the morph he watched
    textureIndex = zeros(1,N);
    for s=1:N
        IM{s} = imread([facesPath,'\originals\',num2str(Originals(s)),'.jpg']);
        textureIndex(1,s) = Screen('MakeTexture', windowPtr, IM{s});
    end
    
    hebWhichFig = [1489,1495,1512,47,1497,32,1489,1508,1512,1510,1493,1507,32,1492,1491,1493,1502,1492,32,1489,1497,1493,1514,1512,32,1500,1508,1512,1510,1493,1507,32,1492,1511,1493,1491,1501];
    if flipText=='y'
        hebWhichFig=flip(hebWhichFig);
    end
    DrawFormattedText(windowPtr, hebWhichFig,'center',(screenYpixels/5),[255 255 255]);
    Screen('DrawTextures', windowPtr, textureIndex, [] ,locationN');
    [~, StimOnset] = Screen('Flip', windowPtr); % dontClear flag is set to 1 to overdraw the frame on the figure
    PsychHID('KbQueueFlush',[], 3); %Flushes all scored and unscored keyboard events from a queue.
    [event,~] = PsychHID('KbQueueGetEvent',[],3); % collect response - Max 3 seconds%
    
    % check the response
    if ~isempty(event)
        keypress = event.Keycode;
        switch keypress
            case leftKey%left arrow
                sel=1;
                Response(trial) =  sel;
                RT(trial) = event.Time-StimOnset;
                subjectChoice(trial) = Originals(sel);
                if ismember(morphNum,morphs_division(Originals(1),:))  %check if the morph closer to this original face
                    correct(trial) = 1;
                elseif ismember(morphNum,morphs_division(2:3,:))%check if the morph closer the other original faces
                    correct(trial) = -1;
                end
                Screen('DrawTextures', windowPtr, textureIndex, [] ,locationN');
                Screen('FrameRect',windowPtr,[237 177 32],locationN(1,:),8)
                Screen('Flip', windowPtr);
                WaitSecs(0.2) % 200 ms in addition to the 500 ms at the end of the trial
                trial=trial+1;
                
            case downKey%down arrow
                sel=2;
                Response(trial) =  sel;
                RT(trial) = event.Time-StimOnset;
                subjectChoice(trial) = Originals(sel);
                if ismember(morphNum,morphs_division(Originals(2),:))  %check if the morph closer top this original face
                    correct(trial) = 1;
                elseif ismember(morphNum,morphs_division(1,3,:))%check if the morph closer the other original faces
                    correct(trial) = -1;
                end
                Screen('DrawTextures', windowPtr, textureIndex, [] ,locationN');
                Screen('FrameRect',windowPtr,[237 177 32],locationN(2,:),8)
                Screen('Flip', windowPtr);
                WaitSecs(0.2) % 200 ms in addition to the 500 ms at the end of the trial
                trial=trial+1;
            case  rightKey%right arrow
                sel=3;
                Response(trial) =  sel;
                RT(trial) = event.Time-StimOnset;
                subjectChoice(trial) = Originals(sel);
                if ismember(morphNum,morphs_division(Originals(3),:))  %check if the morph closer top this original face
                    correct(trial) = 1;
                elseif ismember(morphNum,morphs_division(1:2,:))%check if the morph closer the other original faces
                    correct(trial) = -1;
                end
                Screen('DrawTextures', windowPtr, textureIndex, [] ,locationN');
                Screen('FrameRect',windowPtr,[237 177 32],locationN(3,:),8)
                Screen('Flip', windowPtr);
                WaitSecs(0.2) % 200 ms in addition to the 500 ms at the end of the trial
                trial=trial+1;
            case escapeKey % Esc
                PsychHID('KbQueueFlush',[], 3); %Flushes all scored and unscored keyboard events from a queue.
                PsychHID('KbQueueRelease');
                Screen('CloseAll')
                break;
            otherwise
                wrongKey = [1502,1511,1513,32,1513,1490,1493,1497,32];
                if flipText=='y'
                    wrongKey=flip(wrongKey);
                end
                DrawFormattedText(windowPtr, wrongKey,'center','center',[255 255 255]);
                Screen('Flip', windowPtr);
                WrongKeyTrial(WK) = trial;
                WrongKeyMorph(WK) = morphNum;
                WK=WK+1;
        end
        
    else %no response
        tooSlow = [1504,1490,1502,1512,32,1492,1494,1502,1503,32];
        if flipText=='y'
          tooSlow=flip(tooSlow);
        end
        DrawFormattedText(windowPtr, tooSlow,'center','center',[255 255 255]);
        Screen('Flip', windowPtr);
        TooSlowTrial(TS) = trial;
        TooSlowMorph(TS) = morphNum;
        TS=TS+1;

    end

    WaitSecs(0.5)
end
endTime = GetSecs;
%% show points
Reward = sum(correct.*RewardMagnitude);
cumulativeReward = Reward;
accumWinnings = cumulativeReward+accumWinnings;

%% End remarks
% first screen - winnings in this part
hebWinnings = [1495,1500,1511,32,1494,1492,32,1492,1505,1514,1497,1497,1501,46,32,1505,1498,32,1492,1504,1497,1511,1493,1491,32,1513,1510,1489,1512,1514,32,1489,1495,1500,1511,32,1494,1492,58,32];
if flipText=='y'
   hebWinnings=flip(hebWinnings);
end
DrawFormattedText(windowPtr, [hebWinnings, double(num2str(cumulativeReward))],'center','center',[255 255 255]);
Screen('Flip',windowPtr);
WaitSecs(3);
% second screen - all accumulating winnings
hebAllWinnings = [1502,1505,1508,1512,32,1492,1504,1511,1493,1491,1493,1514,32,1492,1499,1493,1500,1500,32,1513,1510,1489,1512,1514,58,32];
if flipText=='y'
   hebAllWinnings=flip(hebAllWinnings);
end
DrawFormattedText(windowPtr, [hebAllWinnings, double(num2str(accumWinnings))],'center','center',[255 255 255]);
Screen('Flip',windowPtr);
WaitSecs(3);

ShowCursor()
%% saving parameters
log = struct;
log.RT = RT;
log.correct = correct;
log.shuffledTrialsOrder = shuffledTrialsOrder; % The specific order of trials for this participant
log.originalOrder = originalOrder; % The indices to put in the prameters to organize back in the original order ( [~, originalOrder] = sort(shuffledTrialsOrder) )
log.Response = Response; % the response of the participate for left(1) or right(2) arrow
log.ExpTime = endTime - startTime;
log.faces = Originals;
log.subjectChoice = subjectChoice;
log.wrongKeyTrial = WrongKeyTrial;
log.wrongKeyMorph = WrongKeyMorph;
log.tooSlowTrial = TooSlowTrial;
log.tooSlowMorph = TooSlowMorph;
log.cumulativeReward = cumulativeReward;
log.rewardMagnitude = RewardMagnitude;
log.RT_training = RT_training;
log.Response_training = Response_training;
log.wrongKeyTrial_training = WrongKeyTrial_training;
log.wrongKeyMorph_training = WrongKeyMorph_training;
log.tooSlowTrial_training = TooSlowTrial_training;
log.tooSlowMorph_training = TooSlowMorph_training;
% close keyboard queue
PsychHID('KbQueueRelease');

end